services:
  tf:
    image: hashicorp/terraform:1.13.3
    volumes:
      - ./setup:/tf-code/setup
      - ./deploy:/tf-code/deploy
      # Mount your ~/.aws credentials
      - ~/.aws:/root/.aws:ro
      # - ~/.ssh:/root/.ssh:ro
    working_dir: /tf-code
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - TF_WORKSPACE=${TF_WORKSPACE}
